bot:
  name: pchel_test_bot
  token: 1273448729:AAEsX77rwpBf-i1iYFLkbvOFctnUEVsY6vc

mockServer:
  URL: https://serene-coast-56441.herokuapp.com/api/

useMockServerClient: false

spring:
  datasource:
    url: jdbc:postgresql://ec2-3-224-38-18.compute-1.amazonaws.com:5432/dciq3sp6s9ri2j
    username: gyrggouqtcjoqi
    password: 32a6208be646737b54e82d0103a4bd04441f312fa19ba249a79024af92763a32
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.default_schema: PUBLIC
      org.hibernate.envers.audit_table_suffix: _hist
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml